name: Build and Upload Unsupported XPI

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git fetch --tags

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip make

      - name: Build XPI
        run: make xpi

      - name: Upload XPI to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/minimizeonclose.xpi
